### ISSUE TITLE
Where is the dataset of DLPFC?

### ISSUE THREAD

**Issue by LiWZ19** [CSOgroup/cellcharter_analyses#2]
Did not find this dataset within data/

**Comment by marcovarrone** [comment]
Hi @LiWZ19, since it's not possible to upload big files on Github, I uploaded the datasets on Figshare.

The link is in the README, let me know if everything is set up correctly :)
If you want to have a very well standardized preprocessed dataset I highly suggest you to head over the [SpaceHack2023 repository](https://github.com/SpatialHackathon/SpaceHack2023). 
They are doing an amazing work to standardize the preprocessing and benchmarking of these datasets, including the DLPFC.

Fixed by fd63ac5585a3f18846a0891e120864179d4ca429
